// Re-export all types from schema
export type {
	EventType,
	CalendarItem,
	CalendarGetInput,
	CalendarGetOutput,
	IdeaTripCreateInput,
	IdeaTripOutput,
	IdeaTripUpdateInput,
	IdeaTripDeleteInput,
	IdeaTripConfirmInput,
	IdeaTripConfirmOutput,
	IdeaMonthlyCreateInput,
	IdeaMonthlyOutput,
	IdeaMonthlyUpdateInput,
	IdeaMonthlyDeleteInput,
	IdeaMonthlyConfirmInput,
	IdeaMonthlyConfirmOutput,
	BlockedPeriodCreateInput,
	BlockedPeriodOutput,
	BlockedPeriodUpdateInput,
	BlockedPeriodDeleteInput,
	Suggestion,
	Destination,
	DestinationsListInput,
	DestinationsListOutput,
	DestinationCreateInput,
	DestinationUpdateInput,
	DestinationDeleteInput,
	SettingsGetInput,
	SettingsGetOutput,
} from '../schema'
