/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CFamilyIdRouteImport } from './routes/c/$familyId'
import { Route as CFamilyIdIndexRouteImport } from './routes/c/$familyId/index'
import { Route as CFamilyIdSettingsRouteImport } from './routes/c/$familyId/settings'
import { Route as CFamilyIdDestinationsRouteImport } from './routes/c/$familyId/destinations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CFamilyIdRoute = CFamilyIdRouteImport.update({
  id: '/c/$familyId',
  path: '/c/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CFamilyIdIndexRoute = CFamilyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CFamilyIdRoute,
} as any)
const CFamilyIdSettingsRoute = CFamilyIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CFamilyIdRoute,
} as any)
const CFamilyIdDestinationsRoute = CFamilyIdDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => CFamilyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$familyId': typeof CFamilyIdRouteWithChildren
  '/c/$familyId/destinations': typeof CFamilyIdDestinationsRoute
  '/c/$familyId/settings': typeof CFamilyIdSettingsRoute
  '/c/$familyId/': typeof CFamilyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$familyId/destinations': typeof CFamilyIdDestinationsRoute
  '/c/$familyId/settings': typeof CFamilyIdSettingsRoute
  '/c/$familyId': typeof CFamilyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$familyId': typeof CFamilyIdRouteWithChildren
  '/c/$familyId/destinations': typeof CFamilyIdDestinationsRoute
  '/c/$familyId/settings': typeof CFamilyIdSettingsRoute
  '/c/$familyId/': typeof CFamilyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/$familyId'
    | '/c/$familyId/destinations'
    | '/c/$familyId/settings'
    | '/c/$familyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$familyId/destinations'
    | '/c/$familyId/settings'
    | '/c/$familyId'
  id:
    | '__root__'
    | '/'
    | '/c/$familyId'
    | '/c/$familyId/destinations'
    | '/c/$familyId/settings'
    | '/c/$familyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CFamilyIdRoute: typeof CFamilyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$familyId': {
      id: '/c/$familyId'
      path: '/c/$familyId'
      fullPath: '/c/$familyId'
      preLoaderRoute: typeof CFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$familyId/': {
      id: '/c/$familyId/'
      path: '/'
      fullPath: '/c/$familyId/'
      preLoaderRoute: typeof CFamilyIdIndexRouteImport
      parentRoute: typeof CFamilyIdRoute
    }
    '/c/$familyId/settings': {
      id: '/c/$familyId/settings'
      path: '/settings'
      fullPath: '/c/$familyId/settings'
      preLoaderRoute: typeof CFamilyIdSettingsRouteImport
      parentRoute: typeof CFamilyIdRoute
    }
    '/c/$familyId/destinations': {
      id: '/c/$familyId/destinations'
      path: '/destinations'
      fullPath: '/c/$familyId/destinations'
      preLoaderRoute: typeof CFamilyIdDestinationsRouteImport
      parentRoute: typeof CFamilyIdRoute
    }
  }
}

interface CFamilyIdRouteChildren {
  CFamilyIdDestinationsRoute: typeof CFamilyIdDestinationsRoute
  CFamilyIdSettingsRoute: typeof CFamilyIdSettingsRoute
  CFamilyIdIndexRoute: typeof CFamilyIdIndexRoute
}

const CFamilyIdRouteChildren: CFamilyIdRouteChildren = {
  CFamilyIdDestinationsRoute: CFamilyIdDestinationsRoute,
  CFamilyIdSettingsRoute: CFamilyIdSettingsRoute,
  CFamilyIdIndexRoute: CFamilyIdIndexRoute,
}

const CFamilyIdRouteWithChildren = CFamilyIdRoute._addFileChildren(
  CFamilyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CFamilyIdRoute: CFamilyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
