/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FFamilyIdRouteImport } from './routes/f/$familyId'
import { Route as FFamilyIdIndexRouteImport } from './routes/f/$familyId/index'
import { Route as FFamilyIdSettingsRouteImport } from './routes/f/$familyId/settings'
import { Route as FFamilyIdDestinationsRouteImport } from './routes/f/$familyId/destinations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FFamilyIdRoute = FFamilyIdRouteImport.update({
  id: '/f/$familyId',
  path: '/f/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const FFamilyIdIndexRoute = FFamilyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FFamilyIdRoute,
} as any)
const FFamilyIdSettingsRoute = FFamilyIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FFamilyIdRoute,
} as any)
const FFamilyIdDestinationsRoute = FFamilyIdDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => FFamilyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f/$familyId': typeof FFamilyIdRouteWithChildren
  '/f/$familyId/destinations': typeof FFamilyIdDestinationsRoute
  '/f/$familyId/settings': typeof FFamilyIdSettingsRoute
  '/f/$familyId/': typeof FFamilyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f/$familyId/destinations': typeof FFamilyIdDestinationsRoute
  '/f/$familyId/settings': typeof FFamilyIdSettingsRoute
  '/f/$familyId': typeof FFamilyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f/$familyId': typeof FFamilyIdRouteWithChildren
  '/f/$familyId/destinations': typeof FFamilyIdDestinationsRoute
  '/f/$familyId/settings': typeof FFamilyIdSettingsRoute
  '/f/$familyId/': typeof FFamilyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/f/$familyId'
    | '/f/$familyId/destinations'
    | '/f/$familyId/settings'
    | '/f/$familyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/f/$familyId/destinations'
    | '/f/$familyId/settings'
    | '/f/$familyId'
  id:
    | '__root__'
    | '/'
    | '/f/$familyId'
    | '/f/$familyId/destinations'
    | '/f/$familyId/settings'
    | '/f/$familyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FFamilyIdRoute: typeof FFamilyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$familyId': {
      id: '/f/$familyId'
      path: '/f/$familyId'
      fullPath: '/f/$familyId'
      preLoaderRoute: typeof FFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$familyId/': {
      id: '/f/$familyId/'
      path: '/'
      fullPath: '/f/$familyId/'
      preLoaderRoute: typeof FFamilyIdIndexRouteImport
      parentRoute: typeof FFamilyIdRoute
    }
    '/f/$familyId/settings': {
      id: '/f/$familyId/settings'
      path: '/settings'
      fullPath: '/f/$familyId/settings'
      preLoaderRoute: typeof FFamilyIdSettingsRouteImport
      parentRoute: typeof FFamilyIdRoute
    }
    '/f/$familyId/destinations': {
      id: '/f/$familyId/destinations'
      path: '/destinations'
      fullPath: '/f/$familyId/destinations'
      preLoaderRoute: typeof FFamilyIdDestinationsRouteImport
      parentRoute: typeof FFamilyIdRoute
    }
  }
}

interface FFamilyIdRouteChildren {
  FFamilyIdDestinationsRoute: typeof FFamilyIdDestinationsRoute
  FFamilyIdSettingsRoute: typeof FFamilyIdSettingsRoute
  FFamilyIdIndexRoute: typeof FFamilyIdIndexRoute
}

const FFamilyIdRouteChildren: FFamilyIdRouteChildren = {
  FFamilyIdDestinationsRoute: FFamilyIdDestinationsRoute,
  FFamilyIdSettingsRoute: FFamilyIdSettingsRoute,
  FFamilyIdIndexRoute: FFamilyIdIndexRoute,
}

const FFamilyIdRouteWithChildren = FFamilyIdRoute._addFileChildren(
  FFamilyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FFamilyIdRoute: FFamilyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
